version: '3'
services:
    redis: 
        image: 'redis'
        ports: 
            - 6379:6379
    mongo:
        image: mongo
        ports: 
            - 27017:27017
        volumes: 
            - /home/pvposso/mongodata/mongoDB:/data/db
    node-app:
        ports:
            - 3000:3000
        build:
            context: .
        environment:
            - NODE_ENV=development
            - REDIS_PORT=6379
            - REDIS_HOST=redis
            - MONGODB_URI=mongodb://mongo:27017/zaccounts
            - PORT=3000
        depends_on:
            - redis
            - mongo